# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencapy < Formula
  desc "Your machines, mirrored. Code from anywhere."
  homepage "https://opencapy.dev"
  version "0.2.38"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.38/opencapy_darwin_amd64.tar.gz"
      sha256 "aeaa79e6c072b62a48502c3faf77764ffa86e1cc6686da33cbff3dc1019b1a4e"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.38/opencapy_darwin_arm64.tar.gz"
      sha256 "d2220039c7bf80e542ca1114a213a6a92bdb0c7502d0fe570c86a80d60b27b49"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.38/opencapy_linux_amd64.tar.gz"
      sha256 "aca84b7e8143af10ad3c7babc443487dd008fda89354f66f5ec2b169f63a0c55"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.38/opencapy_linux_arm64.tar.gz"
      sha256 "b1814456fb25be5a51cc1e1a1430efb4aca5c46052d49ef80b8519ed1a599413"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  test do
    system "#{bin}/opencapy", "--help"
  end
end
