# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencapy < Formula
  desc "Your machines, mirrored. Code from anywhere."
  homepage "https://opencapy.dev"
  version "0.2.69"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.69/opencapy_darwin_amd64.tar.gz"
      sha256 "fe911f25c82dc67523d95e2dd2f041846d41e0138ddbe8583044864c4e947ae6"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.69/opencapy_darwin_arm64.tar.gz"
      sha256 "0c8dfdcd91eaba4d5934567b588fc467613905d54dc26e090df911a3c841288a"

      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.69/opencapy_linux_amd64.tar.gz"
      sha256 "01ed9455f27925e84cedc4540dfa68a66bf8f0e94fcf477fccbefd4318286521"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardyc/opencapy/releases/download/v0.2.69/opencapy_linux_arm64.tar.gz"
      sha256 "07ae028c834e8d57aa99001e5c31fffa74e211bcd8090f726aad030fc6ff149b"
      define_method(:install) do
        bin.install "opencapy"
      end
    end
  end

  test do
    system "#{bin}/opencapy", "--help"
  end
end
